### ISSUE TITLE
Could you support mxnet model link corresponding to this ncnn mobilefacenet model

### ISSUE THREAD

**Issue by ailihong** [KangKangLoveCat/insightface_ncnn#3]
Hi,KangKangLoveCat
   Thanks you so much for your open source work.I want to validate the accuracy using mxnet.Thanks again.

**Comment by KangKangLoveCat** [comment]
I translated this ncnn model from mxnet model,this link redirect to this origin mxnet model: https://github.com/deepinsight/insightface/issues/214, you can validate the accuracy using this project: https://github.com/deepinsight/insightface/

**Comment by ailihong** [comment]
Thank you for your reply.Do you mean this model(https://pan.baidu.com/s/1If28BkHde4fiuweJrbicVA).
Thanks.

**Comment by KangKangLoveCat** [comment]
Yes, it's the MobileFaceNet model.

**Comment by ailihong** [comment]
Thanks,I will have a try.
