### ISSUE TITLE
关于arcface.cpp中preprocess输入的图像问题

### ISSUE THREAD

**Issue by aguang1201** [KangKangLoveCat/insightface_ncnn#4]
非常感谢您的开源工作。
关于preprocess(ncnn::Mat img, sst_face info)的第一个参数是通过mtcnn截取的脸部图像还是原始图像呢？
preprocess函数内部在做脸部对齐的时候直接传入了img，是不是应该传入mtcnn截取的脸部图像？
warpAffineMatrix(img, out, M, image_w, image_h)
不知道是不是我哪里理解错了，期待您的解答，谢谢！

**Comment by KangKangLoveCat** [comment]
传入的是最原始的图像，预处理就是通过原始图像仿射变换得到arcface的输入，大小为112x112
